# Generated by Django 4.1.7 on 2023-02-26 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_todo',
            name='date',
            field=models.DateField(default='2000-2-2'),
            preserve_default=False,
        ),
    ]
